version: "2.1"

services:
  postgres:
    image: postgres
    restart: always
    ports: ["5432:5432"]
    networks: [backing-services]
    # volumes: ["data"] # definição de local onde estará exposto o volume persistente
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ENVKEY_PGUSER
      POSTGRES_PASSWORD: ENVKEY_PGPWD
      TZ: "America/Sao_Paulo"
      
  grafana:
    image: grafana/grafana-oss:latest
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["3000:3000"]
    networks: [backing-services]
    # volumes: ["grafana_data"]

networks: # configuação de rede virtual
  backing-services:
    driver: bridge